export const INPUT_VALUE_SAVED = 'INPUT_VALUE_SAVED';
export const INPUT_CONFIRM_PASS_FAILED = 'INPUT_CONFIRM_PASS_FAILED';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const INPUT_CONFIRM_PASS_VALID = 'INPUT_CONFIRM_PASS_VALID';

export const INPUT_DATE_SAVED = 'INPUT_DATE_SAVED';
export const PRINT_DATA = 'PRINT_DATA';
export const INPUT_CONFIRM_PASS_CORRECT = 'INPUT_CONFIRM_PASS_CORRECT';